# Orquestador principal - levanta todos los servicios
include:
  - path: ./infra/docker-compose.infra.yml
  - path: ./monitoring/docker-compose.monitoring.yml
  - path: ./others/docker-compose.others.yml
  - path: ./docs/docker-compose.docs.yml

# Red compartida para todos los servicios
networks:
  hosting-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-hosting
